apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-backend
  template:
    metadata:
      labels:
        app: store-backend
    spec:
      containers:
      - name: backend
        image: store-backend:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: store-backend
spec:
  type: ClusterIP
  selector:
    app: store-backend
  ports:
  - port: 8000
    targetPort: 8000
